// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products_API.Data;

#nullable disable

namespace Products_API.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20231121145029_AddingPhoto")]
    partial class AddingPhoto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Products_API.Data.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26b2934c-227d-44d6-9cec-703de7358cd8"),
                            Category = "Electronics",
                            Name = "Laptop",
                            Photo = "",
                            Price = 999.99m,
                            QuantityInStock = 15
                        },
                        new
                        {
                            Id = new Guid("b1383b11-647f-44dd-ba0d-6e640b903a69"),
                            Category = "Education",
                            Name = "Book",
                            Photo = "",
                            Price = 19.99m,
                            QuantityInStock = 100
                        },
                        new
                        {
                            Id = new Guid("4a294bce-cd42-4ba3-9077-1fe0fadc7b18"),
                            Category = "Electronics",
                            Name = "Headphones",
                            Photo = "",
                            Price = 49.99m,
                            QuantityInStock = 30
                        },
                        new
                        {
                            Id = new Guid("2152fdec-0848-4cf4-a196-0ec494f78de6"),
                            Category = "Apparel",
                            Name = "T-shirt",
                            Photo = "",
                            Price = 12.99m,
                            QuantityInStock = 50
                        },
                        new
                        {
                            Id = new Guid("3a22f41f-05eb-4e4c-a78a-028ddb664308"),
                            Category = "Electronics",
                            Name = "Smartphone",
                            Photo = "",
                            Price = 699.99m,
                            QuantityInStock = 25
                        },
                        new
                        {
                            Id = new Guid("3707d1e4-24a2-4de3-a21b-fec58a2e3636"),
                            Category = "Kitchen",
                            Name = "Coffee Mug",
                            Photo = "",
                            Price = 9.99m,
                            QuantityInStock = 75
                        },
                        new
                        {
                            Id = new Guid("f1abfbe1-5afc-47da-85d9-9ba92fc887b8"),
                            Category = "Home Office",
                            Name = "Desk Lamp",
                            Photo = "",
                            Price = 29.99m,
                            QuantityInStock = 20
                        },
                        new
                        {
                            Id = new Guid("babba11a-cc8b-4caa-9a13-e4a63f1e713f"),
                            Category = "Footwear",
                            Name = "Running Shoes",
                            Photo = "",
                            Price = 79.99m,
                            QuantityInStock = 40
                        },
                        new
                        {
                            Id = new Guid("af3cbc70-13dd-4f53-9318-ff11557693b1"),
                            Category = "Accessories",
                            Name = "Backpack",
                            Photo = "",
                            Price = 39.99m,
                            QuantityInStock = 60
                        },
                        new
                        {
                            Id = new Guid("4096716f-ef86-49e7-9841-b6eb555a1539"),
                            Category = "Electronics",
                            Name = "External Hard Drive",
                            Photo = "",
                            Price = 129.99m,
                            QuantityInStock = 10
                        },
                        new
                        {
                            Id = new Guid("55454457-1d2a-436d-9486-be8bc29bef93"),
                            Category = "Fitness",
                            Name = "Yoga Mat",
                            Photo = "",
                            Price = 24.99m,
                            QuantityInStock = 35
                        },
                        new
                        {
                            Id = new Guid("f86bca1e-ac2c-42a8-9f81-5c0cad4b42c4"),
                            Category = "Stationery",
                            Name = "Pencil Set",
                            Photo = "",
                            Price = 7.99m,
                            QuantityInStock = 80
                        },
                        new
                        {
                            Id = new Guid("fe3d1622-28aa-4106-b7dd-62536786e313"),
                            Category = "Furniture",
                            Name = "Gaming Chair",
                            Photo = "",
                            Price = 199.99m,
                            QuantityInStock = 5
                        },
                        new
                        {
                            Id = new Guid("5da4e262-05d4-4e28-bb85-5b232721931d"),
                            Category = "Accessories",
                            Name = "Sunglasses",
                            Photo = "",
                            Price = 59.99m,
                            QuantityInStock = 45
                        },
                        new
                        {
                            Id = new Guid("fb6d3078-aba8-40f4-a43e-a1a1d69ba7f9"),
                            Category = "Electronics",
                            Name = "Bluetooth Speaker",
                            Photo = "",
                            Price = 89.99m,
                            QuantityInStock = 18
                        },
                        new
                        {
                            Id = new Guid("c6df95d1-b096-4212-b019-9d981e576626"),
                            Category = "Stationery",
                            Name = "Notebook",
                            Photo = "",
                            Price = 4.99m,
                            QuantityInStock = 120
                        },
                        new
                        {
                            Id = new Guid("79c3763f-ecd9-4624-b15b-c980c36ab384"),
                            Category = "Gardening",
                            Name = "Gardening Gloves",
                            Photo = "",
                            Price = 14.99m,
                            QuantityInStock = 55
                        },
                        new
                        {
                            Id = new Guid("c9e06bd4-1b6a-4604-a9eb-44979fd0fb89"),
                            Category = "Kitchen",
                            Name = "Cooking Utensils Set",
                            Photo = "",
                            Price = 29.99m,
                            QuantityInStock = 25
                        },
                        new
                        {
                            Id = new Guid("0353626d-87f2-4298-b586-622a3178cc58"),
                            Category = "Travel",
                            Name = "Hiking Backpack",
                            Photo = "",
                            Price = 69.99m,
                            QuantityInStock = 30
                        },
                        new
                        {
                            Id = new Guid("762d5f2e-f41c-411d-83a2-5197b1245570"),
                            Category = "Electronics",
                            Name = "Power Bank",
                            Photo = "",
                            Price = 49.99m,
                            QuantityInStock = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
